#!/bin/sh
SRCD=~/rpi3-opencv/opencv/
cp ${SRCD}modules/ts/include/opencv2/ts/ocl_perf.hpp modules/ts/include/opencv2/ts/ocl_perf.hpp
cp ${SRCD}modules/ts/include/opencv2/ts/ts_gtest.h modules/ts/include/opencv2/ts/ts_gtest.h
cp ${SRCD}modules/ts/include/opencv2/ts/ts_perf.hpp modules/ts/include/opencv2/ts/ts_perf.hpp
cp ${SRCD}modules/ts/include/opencv2/ts/ocl_test.hpp modules/ts/include/opencv2/ts/ocl_test.hpp
cp ${SRCD}modules/ts/include/opencv2/ts/ts_ext.hpp modules/ts/include/opencv2/ts/ts_ext.hpp
cp ${SRCD}modules/ts/include/opencv2/ts.hpp modules/ts/include/opencv2/ts.hpp
cp ${SRCD}modules/ts/src/ts_perf.cpp modules/ts/src/ts_perf.cpp
cp ${SRCD}modules/ts/src/ts_gtest.cpp modules/ts/src/ts_gtest.cpp
cp ${SRCD}modules/ts/src/precomp.hpp modules/ts/src/precomp.hpp
cp ${SRCD}modules/ts/src/ts_func.cpp modules/ts/src/ts_func.cpp
cp ${SRCD}modules/ts/src/ts.cpp modules/ts/src/ts.cpp
cp ${SRCD}modules/ts/src/ocl_perf.cpp modules/ts/src/ocl_perf.cpp
cp ${SRCD}modules/ts/src/ocl_test.cpp modules/ts/src/ocl_test.cpp
cp ${SRCD}modules/features2d/test/ocl/test_brute_force_matcher.cpp modules/features2d/test/ocl/test_brute_force_matcher.cpp
cp ${SRCD}modules/features2d/test/ocl/test_feature2d.cpp modules/features2d/test/ocl/test_feature2d.cpp
cp ${SRCD}modules/features2d/test/test_precomp.hpp modules/features2d/test/test_precomp.hpp
cp ${SRCD}modules/video/test/ocl/test_bgfg_mog2.cpp modules/video/test/ocl/test_bgfg_mog2.cpp
cp ${SRCD}modules/video/test/ocl/test_dis.cpp modules/video/test/ocl/test_dis.cpp
cp ${SRCD}modules/video/test/ocl/test_optflow_farneback.cpp modules/video/test/ocl/test_optflow_farneback.cpp
cp ${SRCD}modules/video/test/ocl/test_optflowpyrlk.cpp modules/video/test/ocl/test_optflowpyrlk.cpp
cp ${SRCD}modules/video/test/test_precomp.hpp modules/video/test/test_precomp.hpp
cp ${SRCD}modules/photo/test/ocl/test_denoising.cpp modules/photo/test/ocl/test_denoising.cpp
cp ${SRCD}modules/photo/test/test_precomp.hpp modules/photo/test/test_precomp.hpp
cp ${SRCD}modules/core/test/ocl/test_dft.cpp modules/core/test/ocl/test_dft.cpp
cp ${SRCD}modules/core/test/ocl/test_gemm.cpp modules/core/test/ocl/test_gemm.cpp
cp ${SRCD}modules/core/test/ocl/test_channels.cpp modules/core/test/ocl/test_channels.cpp
cp ${SRCD}modules/core/test/ocl/test_image2d.cpp modules/core/test/ocl/test_image2d.cpp
cp ${SRCD}modules/core/test/ocl/test_arithm.cpp modules/core/test/ocl/test_arithm.cpp
cp ${SRCD}modules/core/test/ocl/test_matrix_operation.cpp modules/core/test/ocl/test_matrix_operation.cpp
cp ${SRCD}modules/core/test/ocl/test_opencl.cpp modules/core/test/ocl/test_opencl.cpp
cp ${SRCD}modules/core/test/ocl/test_matrix_expr.cpp modules/core/test/ocl/test_matrix_expr.cpp
cp ${SRCD}modules/core/test/test_precomp.hpp modules/core/test/test_precomp.hpp
cp ${SRCD}modules/core/include/opencv2/core/private.hpp modules/core/include/opencv2/core/private.hpp
cp ${SRCD}modules/stitching/test/ocl/test_warpers.cpp modules/stitching/test/ocl/test_warpers.cpp
cp ${SRCD}modules/stitching/test/test_precomp.hpp modules/stitching/test/test_precomp.hpp
cp ${SRCD}modules/stitching/include/opencv2/stitching/warpers.hpp modules/stitching/include/opencv2/stitching/warpers.hpp
cp ${SRCD}modules/imgproc/test/ocl/test_blend.cpp modules/imgproc/test/ocl/test_blend.cpp
cp ${SRCD}modules/imgproc/test/ocl/test_boxfilter.cpp modules/imgproc/test/ocl/test_boxfilter.cpp
cp ${SRCD}modules/imgproc/test/ocl/test_canny.cpp modules/imgproc/test/ocl/test_canny.cpp
cp ${SRCD}modules/imgproc/test/ocl/test_color.cpp modules/imgproc/test/ocl/test_color.cpp
cp ${SRCD}modules/imgproc/test/ocl/test_filter2d.cpp modules/imgproc/test/ocl/test_filter2d.cpp
cp ${SRCD}modules/imgproc/test/ocl/test_filters.cpp modules/imgproc/test/ocl/test_filters.cpp
cp ${SRCD}modules/imgproc/test/ocl/test_gftt.cpp modules/imgproc/test/ocl/test_gftt.cpp
cp ${SRCD}modules/imgproc/test/ocl/test_histogram.cpp modules/imgproc/test/ocl/test_histogram.cpp
cp ${SRCD}modules/imgproc/test/ocl/test_houghlines.cpp modules/imgproc/test/ocl/test_houghlines.cpp
cp ${SRCD}modules/imgproc/test/ocl/test_imgproc.cpp modules/imgproc/test/ocl/test_imgproc.cpp
cp ${SRCD}modules/imgproc/test/ocl/test_match_template.cpp modules/imgproc/test/ocl/test_match_template.cpp
cp ${SRCD}modules/imgproc/test/ocl/test_medianfilter.cpp modules/imgproc/test/ocl/test_medianfilter.cpp
cp ${SRCD}modules/imgproc/test/ocl/test_pyramids.cpp modules/imgproc/test/ocl/test_pyramids.cpp
cp ${SRCD}modules/imgproc/test/ocl/test_sepfilter2d.cpp modules/imgproc/test/ocl/test_sepfilter2d.cpp
cp ${SRCD}modules/imgproc/test/ocl/test_warp.cpp modules/imgproc/test/ocl/test_warp.cpp
cp ${SRCD}modules/imgproc/test/test_precomp.hpp modules/imgproc/test/test_precomp.hpp
cp ${SRCD}modules/imgproc/src/hal_replacement.hpp modules/imgproc/src/hal_replacement.hpp
cp ${SRCD}modules/imgproc/src/precomp.hpp modules/imgproc/src/precomp.hpp
cp ${SRCD}modules/imgproc/src/_geom.h modules/imgproc/src/_geom.h
cp ${SRCD}modules/imgproc/src/filterengine.hpp modules/imgproc/src/filterengine.hpp
